version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: pg-auth
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password@123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  spring-app:
    build: .
    container_name: spring-auth-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Password@123
      JWT_SECRET_KEY: mySuperSecretKeyForJWT1234567890!!
      JWT_ACCESS_TOKEN_VALIDITY: 300000
      JWT_REFRESH_TOKEN_VALIDITY: 604800000

volumes:
  pgdata:
